### ISSUE TITLE
Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderArray initWithObjects:count:]: attempt to insert nil object from objects[1]'

### ISSUE THREAD

**Issue by robinsenior** [reidmain/FDFoundationKit#4]
I have experienced a crash in -[FDCache allObjects] :  75 (return _weakDictionary.allValues;)

Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderArray initWithObjects:count:]: attempt to insert nil object from objects[1]'

If I po _weakDictionary I see:

{
    atp = "&lt;TSLeague: 0x174192bd0&gt;";
    bund = "&lt;TSLeague: 0x1701934c0&gt;";
    cfl = "&lt;TSLeague: 0x170192d70&gt;";
    chlg = "&lt;TSLeague: 0x174192d70&gt;";
    engcc = "&lt;TSLeague: 0x174193180&gt;";
    engfa = "&lt;TSLeague: 0x1741930b0&gt;";
    epga = "&lt;TSLeague: 0x1701938d0&gt;";
    epl = "&lt;TSLeague: 0x174192fe0&gt;";
    espcr = "&lt;TSLeague: 0x170193250&gt;";
    eurc = "&lt;TSLeague: 0x174382a40&gt;";
    eurcq = "&lt;TSLeague: 0x174382ff0&gt;";
    fmf = "&lt;TSLeague: 0x174193250&gt;";
    formula1 = "&lt;TSLeague: 0x174192b00&gt;";
    fran = "&lt;TSLeague: 0x170193660&gt;";
    gerdfbp = "&lt;TSLeague: 0x170193590&gt;";
    itaci = "&lt;TSLeague: 0x1701933f0&gt;";
    liga = "&lt;TSLeague: 0x170193180&gt;";
    lpga = "&lt;TSLeague: 0x1701939a0&gt;";
    mlb = "&lt;TSLeague: 0x170192ca0&gt;";
    mls = "&lt;TSLeague: 0x174192f10&gt;";
    mma = "&lt;TSLeague: 0x170192f10&gt;";
    nascar = "&lt;TSLeague: 0x170192fe0&gt;";
    nasnw = "&lt;TSLeague: 0x170387840&gt;";
    nba = "&lt;TSLeague: 0x170192b00&gt;";
    ncaab = "&lt;TSLeague: 0x170192e40&gt;";
    ncaaf = "&lt;TSLeague: 0x170192bd0&gt;";
    nfl = "&lt;TSLeague: 0x170192a30&gt;";
    nhl = "&lt;TSLeague: 0x1741927c0&gt;";
    nll = "&lt;TSLeague: 0x170193730&gt;";
    pga = "&lt;TSLeague: 0x174192a30&gt;";
    pga2 = "&lt;TSLeague: 0x170193800&gt;";
    seri = "&lt;TSLeague: 0x170193320&gt;";
    uefa = "&lt;TSLeague: 0x174192e40&gt;";
    wcbk = "&lt;TSLeague: 0x1701930b0&gt;";
    wjhc = "&lt;TSLeague: 0x170192890&gt;";
    wolymhm = "&lt;TSLeague: 0x170388bc0&gt;";
    wolymhw = "&lt;TSLeague: 0x170388af0&gt;";
    worldcup = "&lt;TSLeague: 0x174380820&gt;";
    wta = "&lt;TSLeague: 0x174192ca0&gt;";
}

**Comment by reidmain** [comment]
Found the crash. FDCache relies on an NSCache and an FDWeakMutableDictionary internally. If an object inside the FDWeakMutableDictionary has been released from the NSCache and is referenced nowhere else in the application the `- (id)objectForKey: (id)key` method inside FDWeakMutableDictionary will return nil for the key associated with that object. `allObjects` seems to iterate over all the keys of the FDWeakMutableDictionary and simply adds the result of `objectForKey:` to an array because it makes the assumption that no object in the array can be nil (which is obviously true for NSDictionary). This obviously causes an exception because you can't add nil to a NSMutableArray.

The solution is to just override allObjects inside FDWeakMutableDictionary and check if the result of `objectForKey:` is nil before adding it to the array.

**Comment by reidmain** [comment]
Fixed with the commit https://github.com/reidmain/FDFoundationKit/commit/239fc895d648af3de825d29c4122d03a458dbc4e
